# Generated by Django 5.2.14 on 2026-06-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prompttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='template',
            field=models.TextField(help_text='Use Python format placeholders such as {topic}, {platform}, {tone}, {audience}, {count}, {post_type}, {category}, {voice_context}, {research_data}, {draft_content}, and {generated_content}.'),
        ),
    ]
