from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/settings/', views.dashboard_settings, name='dashboard_settings'),
    path('dashboard/prompts/', views.prompt_settings, name='prompt_settings'),
    path('content-topics/', views.content_topics, name='content_topics'),
    path('content-topics/<int:post_id>/edit/', views.edit_content_topic, name='edit_content_topic'),
    path('content-topics/<int:post_id>/delete/', views.delete_content_topic, name='delete_content_topic'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    path('logout/', views.logout_view, name='logout'),
    path('onboarding/', views.onboarding_view, name='onboarding'),
    path('topic-generator/', views.generate_topics_view, name='generate_topics'),
    path('topic-generator/manual/', views.manual_topic_view, name='manual_topic'),
    path('topic-generator/save/', views.save_generated_topic, name='save_generated_topic'),
    path('excel-upload/', views.upload_csv, name='upload_csv'),
    path('excel-upload/demo/', views.download_demo_excel, name='download_demo_excel'),
    path('email-integration/', views.email_integration, name='email_integration'),
    path('email-integration/<int:recipient_id>/toggle/', views.toggle_email_recipient, name='toggle_email_recipient'),
    path('email-integration/<int:recipient_id>/delete/', views.delete_email_recipient, name='delete_email_recipient'),
    path('review/', views.review_dashboard, name='review_dashboard'),
    path('review/<int:post_id>/approve/', views.approve_post, name='approve_post'),
    path('review/<int:post_id>/reject/', views.reject_post, name='reject_post'),
    path('review/<int:post_id>/regenerate/', views.regenerate_post, name='regenerate_post'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/published/', views.mark_post_published, name='mark_post_published'),
    path('post/<int:post_id>/advanced-ai/<str:tool>/', views.advanced_ai_action, name='advanced_ai_action'),
    path('history/', views.history_view, name='history_view'),
    path('trigger-cron/', views.trigger_cron, name='trigger_cron'),
]
